# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 2345签到

on:
  workflow_dispatch:
  # push:
  pull_request:
  watch:
    types: started
  schedule:
    - cron: "0 9 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          ref: 2345
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 2345签到
        run: |
          python3 2345.py 
        env: 
          WPLM_COOKIE: ${{ secrets.WPLM_COOKIE }}
