# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CSDN签到&抽奖

on:
  workflow_dispatch:
  # push:
  pull_request:
  watch:
    types: started
  schedule:
    - cron: "0 16 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          ref: CSDN
     - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: CSDN
      run: |
        python3 CSDN.py 
      env: 
        CSDN_ID: ${{ secrets.CSDN_ID }}
        COOKIE: ${{ secrets.CSDN_COOKIE }}
        IF_LUCK_DRAW: ${{ secrets.IF_LUCK_DRAW }}
        IF_SEVER: ${{ secrets.IF_SEVER }}
        IF_WECHAT: ${{ secrets.IF_WECHAT }}
        IF_DING: ${{ secrets.IF_DING }}
        SEVER_SCKEY: ${{ secrets.SEVER_SCKEY }}
        WECHAT_URL: ${{ secrets.WECHAT_URL }}
        DING_URL: ${{ secrets.DING_URL }}
        DING_SECRET: ${{ secrets.DING_SECRET }}