#https://raw.githubusercontent.com/h455257166/AutoUpdateScripts/MiGuAiKan10086/migu.sh

name: 咪咕爱看签到(main)

on:
  workflow_dispatch:
  # push:
  pull_request:
  watch:
    types: started
  schedule:
    - cron: '0 0,1,2 * * *'
    #北京时间八点九点十点运行，北京时间=国际时间+8小时
  
jobs:
  migu-sign:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: sign
      env:
        MIGUCOOKIE1: ${{ secrets.MIGUCOOKIE1 }}
        MIGUCOOKIE2: ${{ secrets.MIGUCOOKIE2 }}
        MIGUCOOKIE3: ${{ secrets.MIGUCOOKIE3 }}
        MIGUCOOKIE4: ${{ secrets.MIGUCOOKIE4 }}
      run: |
        bash <(curl -sSL https://raw.githubusercontent.com/h455257166/AutoUpdateScripts/MiGuAiKan10086/migu.sh)
        
